### PR TITLE
Add `mob-print --initials` for coAuthors initials

### PR DESCRIPTION
**Pull request by joelash**
The main goal of this is to allow for adding a list of initials for the current CoAuthors in your PS1.

### CODE REVIEW

**Comment by manicolosi** [comment]
I need for my zsh prompt!

**Comment by rkotze** [comment]
@joelash Thanks for the PR. Looks good, I'll add it in. Can you provide a usage example in the readme please.

**Comment by joelash** [comment]
@rkotze I added a usage in the README, let me know if you think it's clear enough.

**Comment by rkotze** [comment]
I've resolved these conflicts and merged into `findmypast-oss/master`. I'll make a release soon. Thanks for your contribution. 👍

**Comment by rkotze** [comment]
@joelash your changes have been released in v1 https://github.com/findmypast-oss/git-mob/releases

**Pull request closed without merging**
