### PR TITLE
Override main author feature + merge conflict resolution

### LINKED ISSUE #26: Overide default user
will be nice an option for override the default user.

we use a common Mac for IOS and we do mob programming bus the default user is not always the same

something like
`git mob -o in1 in2 in3`

set commiter as in1 and co author as in2 and in3

### PR DESCRIPTION
**Pull request by eric-thelin**
This is a combination of #27 by @Sarabadu and resolutions to the merge conflicts incurred when trying to merge with the original code base.

Fixes #26

### CODE REVIEW

**Comment by rkotze** [comment]
Thanks for resolving the conflicts for this feature @eric-thelin. Just to let you know I will review this soon and provide feedback if needed.

**Comment by eric-thelin** [comment]
Thank you!

**Comment by rkotze** [comment]
@eric-thelin @Sarabadu Sorry for the slow review. Couple of things.

- I ran the tests on windows and unfortunately the test did not work. Are you able to run on windows? I can look further into it.
- Could  you update the readme with an example usage of the command?

**Comment by rkotze** [comment]
@eric-thelin & @Sarabadu your changes have been released in v1 https://github.com/findmypast-oss/git-mob/releases

**Pull request merged**
