### PR TITLE
Suggest coauthors

### PR DESCRIPTION
**Pull request by mocoso**
Add a suggest-coauthors command

Often the people you will be pairing with have already authored commits on the repo you are working on. This command makes it as easy as possible to add an existing author from the current repo to your list of co-authors.

Example usage

```bash    
$ git suggest-coauthors

Here are some suggestions for co-authors based on existing authors of this repository
    
git add-coauthor aa "Alice Apple" alice@acme.example
git add-coauthor bo "Bob Orange" bob@acme.example
git add-coauthor cb "Charlie Banana" charlie@acme.example

Paste any line above into your console to add them as a co-author
```

### CODE REVIEW

**Comment by rkotze** [comment]
Hi, @mocoso Sorry for the slow review.

Thanks for the PR, I really like this idea and printing the command to add a co-author is a clean solution.

- One issue I had was the command did not work on my machine, which is running Windows 10. It complained about not finding the dir for `/dev/tty`. However, I tried replacing it with `CON:` and that fixed the issue but the formatting broke. 

**Idea:** I've implemented a similar feature on [Git Mob VS Code extension](https://github.com/rkotze/git-mob-vs-code), running this command seems to work cross-platform [git repo authors](https://github.com/rkotze/git-mob-vs-code/blob/master/src/git/commands.js#L80).

- Something else to think about is to limit the suggestions as you might be in a repo which many people have contributed to. Especially over time. Ideas: Perhaps a filter by name or top 10 contributes.

**Comment by mocoso** [comment]
@rkotze: Thanks for the feedback - I have changed the `git shortlog` command to provide a commit `HEAD` (as you did in your extension) so that it doesn't expect input and this removes the need for `/dev/tty`.

I have also moved this call to git-commands.js and gused `silentRun` to match your other command line calls to git.

I think that it is interesting to consider how to limit the suggestions for repos with very large numbers of contributors but given that this is likely to be the minority of repos perhaps we could release it as is and then if it gets use we can consider adding further complexity to it.

**Comment by rkotze** [comment]
> I think that it is interesting to consider how to limit the suggestions for repos with very large numbers of contributors but given that this is likely to be the minority of repos perhaps you could release it as is and then if it gets use we can consider adding further complexity to it.

@mocoso  I'm happy to apply the filtering complexity to another release.

I'll review the code soon. Thanks

**Comment by mocoso** [comment]
@rkotze is there anything I can do to help?

**Comment by rkotze** [comment]
@mocoso hi, sorry for the slow reply. I will try to get some time this week to get this in.

**Pull request merged**
